name: ${CONTAINER_NAME}
services:
    app:
        build:
            args:
                user: "${UID}:${GID}"
                uid: ${UID}
                APP_ENV: ${APP_ENV}
            context: ./
            dockerfile: Dockerfile
        image: planexx:latest
        container_name: ${CONTAINER_NAME}_app
        restart: unless-stopped
        tty: true
        user: "${UID}:${GID}"
        environment:
            SERVICE_NAME: ${CONTAINER_NAME}
            SERVICE_TAGS: ${APP_ENV}
            CONTAINER_ROLE: app
        working_dir: /var/www
        depends_on:
            -   db
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app_network
        extra_hosts:
            - "host.docker.internal:host-gateway"
        command: >
            sh -c "sh ./standards/hooks/install-hooks.sh && php-fpm"

    webserver:
        image: nginx:1.22
        container_name: ${CONTAINER_NAME}_webserver
        restart: unless-stopped
        tty: true
        ports:
            - "${WEBSERVER_HTTP_PORT}:80"
            - "${WEBSERVER_HTTPS_PORT}:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app_network
        extra_hosts:
            - "host.docker.internal:host-gateway"

    db:
        image: mysql:8.4
        container_name: ${CONTAINER_NAME}_db
        restart: unless-stopped
        tty: true
        #       ports:
        #           - "3307:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            # MYSQL_RANDOM_ROOT_PASSWORD: 1
            SERVICE_TAGS: ${APP_ENV}
            SERVICE_NAME: ${DB_DATABASE}
        volumes:
            - dbdata:/var/lib/mysql/
            # - ~/.dockertmp/lsp/mysql/:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app_network

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: ${CONTAINER_NAME}_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - "${PHPMYADMIN_PORT}:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${CONTAINER_NAME}_db
            - PMA_PORT=3306
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - UPLOAD_LIMIT=600M
        volumes:
            - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        networks:
            - app_network

    redis:
        image: redis:latest
        container_name: ${CONTAINER_NAME}_redis
        restart: always
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        networks:
            - app_network

    node:
        image: node:lts-alpine
        container_name: ${CONTAINER_NAME}_node
        tty: true
        restart: unless-stopped
        user: "${UID}:${GID}"
        volumes:
            - ./:/var/www
        working_dir: /var/www
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
volumes:
    dbdata:
        driver: local
